// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/supplier_search/dao/internal"
)

// internalVendorIndexDao is internal type for wrapping internal DAO implements.
type internalVendorIndexDao = *internal.VendorIndexDao

// vendorIndexDao is the data access object for table hg_fm_vendor_index.
// You can define custom methods on it to extend its functionality as you wish.
type vendorIndexDao struct {
	internalVendorIndexDao
}

var (
	// VendorIndex is globally public accessible object for table hg_fm_vendor_index operations.
	VendorIndex = vendorIndexDao{
		internal.NewVendorIndexDao(),
	}
)

// Fill with you ideas below.
