// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/supplier_search/dao/internal"
)

// internalVendorUploadFileDao is internal type for wrapping internal DAO implements.
type internalVendorUploadFileDao = *internal.VendorUploadFileDao

// vendorUploadFileDao is the data access object for table hg_fm_vendor_upload_file.
// You can define custom methods on it to extend its functionality as you wish.
type vendorUploadFileDao struct {
	internalVendorUploadFileDao
}

var (
	// VendorUploadFile is globally public accessible object for table hg_fm_vendor_upload_file operations.
	VendorUploadFile = vendorUploadFileDao{
		internal.NewVendorUploadFileDao(),
	}
)

// Fill with you ideas below.
