// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/addons/supplier_search/dao/internal"
)

// internalVendorDao is internal type for wrapping internal DAO implements.
type internalVendorDao = *internal.VendorDao

// vendorDao is the data access object for table hg_fm_vendor.
// You can define custom methods on it to extend its functionality as you wish.
type vendorDao struct {
	internalVendorDao
}

var (
	// Vendor is globally public accessible object for table hg_fm_vendor operations.
	Vendor = vendorDao{
		internal.NewVendorDao(),
	}
)

// Fill with you ideas below.
